server:
  port: 8080

spring:
  application:
    name: Classic Spring Data JPA
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
    hikari:
      maximum-pool-size: 100
      minimum-idle: 10
      idle-timeout: 30000
      max-lifetime: 60000
      connection-timeout: 20000

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true
    open-in-view: false

logging:
  level:
    org.hibernate.SQL: off


