server:
  port: 8083
spring:
  application:
    name: Reactive Spring WebFlux + R2DBC
  r2dbc:
    url: r2dbc:h2:mem:///testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true
